"use client";

import Link from "next/link";
import { useState } from "react";

type ListEditorProps = { title: string; hint: string; initial: string[]; tone?: "slate" | "orange" };
function ListEditor({ title, hint, initial, tone = "slate" }: ListEditorProps) {
  const [items, setItems] = useState(initial);
  const [draft, setDraft] = useState("");
  const add = () => { const value = draft.trim(); if (value && !items.some((item) => item.toLowerCase() === value.toLowerCase())) setItems((current) => [...current, value]); setDraft(""); };
  return <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-black">{title}</h2><p className="mt-1 text-sm text-slate-500">{hint}</p><div className="mt-4 flex flex-wrap gap-2">{items.map((item) => <button key={item} onClick={() => setItems((current) => current.filter((value) => value !== item))} className={`rounded-full px-3 py-1.5 text-sm ${tone === "orange" ? "bg-orange-50 text-orange-900" : "bg-slate-100 text-slate-700"}`}>{item} ×</button>)}</div><div className="mt-4 flex gap-2"><input value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); add(); } }} placeholder={`Add ${title.toLowerCase().replace(/s$/, "")}`} className="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm"/><button onClick={add} className="rounded-lg bg-slate-950 px-3 py-2 text-sm font-bold text-white">Add</button></div></section>;
}

const countries = ["Italy", "Germany", "France", "Czechia", "Romania", "Poland", "Netherlands", "Spain", "Portugal", "Sweden", "Denmark", "Finland", "Ireland"];
const remoteOptions = [{ id: "fully_remote", label: "Fully remote", hint: "Can be done from anywhere." }, { id: "restricted_remote", label: "Remote within EU / Europe", hint: "Preserves location restrictions." }, { id: "hybrid", label: "Hybrid", hint: "Some office time is expected." }, { id: "on_site", label: "On-site", hint: "Office-based roles." }];

export default function SettingsPage() {
  const [selectedCountries, setSelectedCountries] = useState(countries);
  const [remoteTypes, setRemoteTypes] = useState(["fully_remote", "restricted_remote", "hybrid"]);
  return <main className="min-h-screen bg-[#f7f8fa] p-6 text-slate-950 sm:p-10"><div className="mx-auto max-w-3xl"><Link href="/" className="text-sm font-bold text-[#d84320]">← Today&apos;s Radar</Link><h1 className="mt-5 text-3xl font-black">Search preferences</h1><p className="mt-2 text-slate-500">These local MVP settings are ready to connect to your account when Supabase is configured.</p><div className="mt-8 space-y-5"><ListEditor title="Desired roles" hint="Use several title variations to maximize discovery recall." initial={["Junior Java Developer", "Java Developer", "Backend Developer", "Software Engineer"]}/><ListEditor title="Positive keywords" hint="Technologies and signals that should boost an opportunity." initial={["Java", "Spring", "Spring Boot", "SQL", "REST", "React", "TypeScript", "PostgreSQL", "MySQL"]} tone="orange"/><ListEditor title="Negative keywords" hint="Roles containing these terms are strongly de-prioritized." initial={["Senior", "Staff", "Principal", "Lead", "Manager", "Director", "Architect"]}/><section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-black">Preferred countries</h2><p className="mt-1 text-sm text-slate-500">Choose the markets you want Radario to prioritize.</p><div className="mt-4 flex flex-wrap gap-2">{countries.map((country) => { const selected = selectedCountries.includes(country); return <button key={country} onClick={() => setSelectedCountries((current) => selected ? current.filter((item) => item !== country) : [...current, country])} className={`rounded-full px-3 py-1.5 text-sm font-medium ${selected ? "bg-slate-950 text-white" : "bg-slate-100 text-slate-600"}`}>{country}</button>; })}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-black">Work model</h2><p className="mt-1 text-sm text-slate-500">Remote geography is intentionally distinct from fully remote.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{remoteOptions.map((option) => { const selected = remoteTypes.includes(option.id); return <button key={option.id} onClick={() => setRemoteTypes((current) => selected ? current.filter((item) => item !== option.id) : [...current, option.id])} className={`rounded-xl border p-4 text-left ${selected ? "border-slate-950 bg-slate-950 text-white" : "border-slate-200 bg-white"}`}><p className="font-bold">{option.label}</p><p className={`mt-1 text-xs ${selected ? "text-slate-300" : "text-slate-500"}`}>{option.hint}</p></button>; })}</div></section></div></div></main>;
}
